(()=>{
  const S=SEIBUN; S.views={};
  const btn=(label,onclick,cls='button primary')=>`<button class="${cls}" onclick="${onclick}">${label}</button>`;
  const typeVisual=(profile,small=false)=>{
    const asset=S.diagnosis.typeAsset(profile);
    if(asset)return `<div class="type-visual ${small?'small':''}"><img src="${asset}" alt="${S.escape(profile.code)} ${S.escape(profile.name)} の仮イラスト"></div>`;
    return `<div class="type-visual abstract ${small?'small':''}"><span></span><i></i><b>TYPE ${profile?.baseNo?String(profile.baseNo).padStart(2,'0'):'--'}</b></div>`;
  };
  const ingredientCards=(recs,profile,limit=recs.length)=>`<div class="ingredient-rec-list">${recs.slice(0,limit).map((r,i)=>`<button class="ingredient-rec" onclick="SEIBUN.showIngredient('${encodeURIComponent(r.name)}')"><span class="rank">${String(i+1).padStart(2,'0')}</span><div><strong>${S.escape(r.name)}</strong><p>${S.escape(r.short)}</p><small>${S.escape(S.ingredients.whyRecommended(r,profile))}</small></div><b>›</b></button>`).join('')}</div>`;

  S.showIngredient=encoded=>{S.state.selectedIngredient=decodeURIComponent(encoded);S.render('ingredientDetail')};
  S.startScanFlow=()=>{if(S.state.profile){S.render('scan');return}S.render('scanGate')};
  S.skipProfileAndScan=()=>{S.render('scan')};
  S.dictionarySearch=q=>{S.state.dictionaryQuery=q;S.state.dictionaryOffset=60;S.render('ingredients',{replace:true,instant:true})};
  S.dictionaryMore=()=>{S.state.dictionaryOffset+=60;S.render('ingredients',{replace:true,instant:true})};

  S.views.home=()=>`<section class="home-screen">
    <div class="home-brand"><span class="brand-orb">S</span><strong>SEIBUNメガネ</strong></div>
    <div class="home-copy"><span class="eyebrow">SKIN × INGREDIENTS</span><h1>肌を知る。<br>成分を見る。</h1><p>肌タイプをチェックして、化粧品の成分表を自分向けに読みやすく。</p></div>
    <div class="home-actions">${btn('60秒で肌タイプをチェック','SEIBUN.diagnosis.startSimple()','button primary xl')}<button class="text-link" onclick="SEIBUN.startScanFlow()">すぐに成分表を読む</button></div>
    <div class="home-links"><button onclick="SEIBUN.render('ingredients')">成分辞典</button><button onclick="SEIBUN.render('aboutDiagnosis')">診断のしくみ</button></div>
  </section>`;

  S.views.simpleDiagnosis=()=>{const i=S.state.simpleIndex,q=SIMPLE_QUESTIONS[i];return `<section class="question-screen"><header class="question-head"><span>QUICK CHECK</span><b>${i+1} / ${SIMPLE_QUESTIONS.length}</b></header><div class="progress-line"><i style="width:${((i+1)/SIMPLE_QUESTIONS.length)*100}%"></i></div><div class="question-body"><p class="question-kicker">約60秒の簡単チェック</p><h1>${S.escape(q.q)}</h1><div class="answer-list">${q.options.map((o,idx)=>`<button onclick="SEIBUN.diagnosis.answerSimple(${idx})"><span>${S.escape(o[0])}</span><b>›</b></button>`).join('')}</div></div><button class="quiet-back" onclick="SEIBUN.back()">あとでやる</button></section>`};

  S.views.simpleResult=()=>{const r=S.state.simpleResult||S.diagnosis.computeSimple(),p=r.profile,recs=S.ingredients.recommendations(p,3);return `<section class="result-screen simple-result"><div class="result-hero"><span class="eyebrow">QUICK RESULT</span><p>今の肌傾向は</p><h1>${S.escape(r.name)}</h1><div class="simple-symbol ${r.type}"><span></span><i></i></div><p>${S.escape(r.summary)}</p></div><section class="content-block"><div class="section-heading"><span>YOUR INGREDIENTS</span><h2>まず見たい成分</h2></div>${ingredientCards(recs,p,3)}</section><section class="next-step-card"><span class="step-label">NEXT STEP</span><h2>もっと詳しく、32タイプへ</h2><p>4つの肌傾向と今の季節を見て、あなたに近いタイプとおすすめ成分を詳しく整理します。</p><div class="next-meta"><span>約4〜5分</span><span>${S.diagnosis.deepQuestions().length}問＋任意2項目</span></div>${btn('じっくり32タイプ診断へ','SEIBUN.render(\'deepIntro\')','button dark wide')}</section><div class="result-actions">${btn('このタイプで商品をスキャン','SEIBUN.render(\'scan\')','button primary wide')}<button class="text-link" onclick="SEIBUN.enablePersist()">この肌設定を端末に保存</button></div></section>`};

  S.views.deepIntro=()=>`<section class="deep-intro"><span class="eyebrow">DEEP CHECK</span><h1>次は、肌を<br>4つの軸で見る。</h1><p>簡単チェックより少しだけ詳しく。1問ずつ答えると、16基本タイプを整理します。最後に性別を任意で選ぶと、最大32プロフィールとして成分の優先度を微調整します。</p><div class="axis-preview"><div><b>01</b><span>うるおい ↔ 皮脂</span></div><div><b>02</b><span>ゆらぎ ↔ 安定</span></div><div><b>03</b><span>色ムラケア ↔ 維持</span></div><div><b>04</b><span>ハリケア ↔ 維持</span></div></div><div class="season-note">${S.seasonLabel(S.currentSeason())}の質問を3問だけ追加します。</div>${btn('じっくり診断をはじめる','SEIBUN.diagnosis.startDeep()','button primary xl wide')}<button class="text-link" onclick="SEIBUN.render('aboutDiagnosis')">診断のしくみを見る</button></section>`;

  S.views.deepDiagnosis=()=>{const qs=S.diagnosis.deepQuestions(),i=S.state.deepIndex,q=qs[i],seasonal=i>=DEEP_BASE_QUESTIONS.length;return `<section class="question-screen deep"><header class="question-head"><span>${seasonal?`${S.seasonLabel(S.currentSeason())}の質問`:'DEEP CHECK'}</span><b>${i+1} / ${qs.length}</b></header><div class="progress-line"><i style="width:${((i+1)/qs.length)*100}%"></i></div><div class="question-body">${seasonal?'<p class="question-kicker">今の季節について、あと少し</p>':'<p class="question-kicker">考えすぎず、今の感覚で</p>'}<h1>${S.escape(q.q)}</h1><div class="answer-list">${q.options.map((o,idx)=>`<button onclick="SEIBUN.diagnosis.answerDeep(${idx})"><span>${S.escape(o[0])}</span><b>›</b></button>`).join('')}</div></div></section>`};

  S.views.demographics=()=>`<section class="demographics-screen"><span class="eyebrow">LAST STEP</span><h1>最後に、よければ。</h1><p>年齢と性別は任意です。回答しなくても結果は見られます。タイプを決める主役は、ここまでのあなたの回答です。</p><label><span>年齢</span><select id="ageSelect">${AGE_OPTIONS.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label><span>性別</span><select id="genderSelect">${GENDER_OPTIONS.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><div class="soft-note">男性／女性を選んだ場合だけ、回答結果を変えすぎない範囲で成分の優先度を微調整し、M01〜M16 / F01〜F16 の32プロフィールとして表示します。</div>${btn('結果を見る','SEIBUN.diagnosis.finishDeep()','button primary xl wide')}</section>`;

  S.views.deepResult=()=>{const p=S.state.profile;if(!p||p.mode!=='deep')return S.views.deepIntro();const recs=S.ingredients.recommendations(p,5),rows=S.diagnosis.axisRows(p);return `<section class="result-screen deep-result"><div class="type-code">${p.code}</div>${typeVisual(p)}<div class="result-hero"><span class="eyebrow">YOUR SKIN TYPE</span><h1>${S.escape(p.name)}</h1><p>${S.escape(p.summary)}</p></div><div class="axis-result">${rows.map(([name,val,label])=>`<div><span><strong>${name}</strong><small>${label}</small></span><div><i style="width:${S.clamp(val,8,100)}%"></i></div></div>`).join('')}</div><p class="profile-note">${S.escape(S.diagnosis.demographicNote(p))}</p><section class="content-block"><div class="section-heading"><span>RECOMMENDED</span><h2>あなたにおすすめの成分</h2><p>成分名をタップすると、説明を詳しく見られます。</p></div>${ingredientCards(recs,p,5)}</section><div class="result-actions">${btn('このタイプで商品をスキャン','SEIBUN.render(\'scan\')','button primary xl wide')}<button class="button ghost wide" onclick="SEIBUN.enablePersist()">この肌タイプを端末に保存</button><button class="text-link" onclick="SEIBUN.render('aboutDiagnosis')">この判定のしくみ</button></div></section>`};

  S.views.aboutDiagnosis=()=>`<section class="plain-page">${S.diagnosis.explanationHtml()}</section>`;

  S.views.scanGate=()=>`<section class="choice-screen"><span class="eyebrow">BEFORE SCAN</span><h1>自分向けに見るなら、<br>先に肌チェック。</h1><p>簡単チェックは約60秒。診断なしでも成分名の読み取りと辞典確認はできます。</p>${btn('60秒チェックをする','SEIBUN.diagnosis.startSimple()','button primary xl wide')}<button class="button ghost wide" onclick="SEIBUN.skipProfileAndScan()">診断なしで成分だけ読む</button></section>`;

  S.views.scan=()=>{const p=S.state.profile;return `<section class="scan-screen"><div class="simple-page-head"><span class="eyebrow">SCAN</span><h1>成分表を撮る。</h1>${p?`<button class="current-type" onclick="SEIBUN.render('${p.mode==='deep'?'deepResult':'simpleResult'}')"><small>現在の肌タイプ</small><strong>${S.escape(p.code?`${p.code}｜${p.name}`:p.name)}</strong><b>›</b></button>`:'<p>肌タイプ未設定。成分の読み取りのみ行います。</p>'}</div><button class="camera-main" onclick="SEIBUN.ocr.openCamera()"><span>◎</span><strong>カメラで撮る</strong><small>全成分が入るように</small></button><button class="button ghost wide" onclick="SEIBUN.ocr.chooseFile()">写真から選ぶ</button><input id="scanInput" class="sr-only" type="file" accept="image/*" capture="environment" onchange="SEIBUN.ocr.fileSelected(event)"><details class="minimal-details"><summary>うまく撮れないとき</summary><div><p>反射を避け、成分欄をまっすぐ大きく写してください。</p><button class="text-link" onclick="SEIBUN.render('manualInput')">成分を手入力・貼り付け</button></div></details></section>`};

  S.views.scanConfirm=()=>`<section class="scan-confirm"><span class="eyebrow">CHECK PHOTO</span><h1>この写真で読む？</h1><div class="photo-preview"><img id="scanPhotoPreview" alt="選択した成分表の写真"></div>${btn('この写真を読み取る','SEIBUN.ocr.startScan()','button primary xl wide')}<button class="text-link" onclick="SEIBUN.ocr.reset()">選び直す</button></section>`;

  S.views.ocrLoading=()=>`<section class="ocr-full"><div class="ocr-top"><span class="eyebrow">READING</span><h1 id="ocrStatus">成分を読み取っています</h1><div class="ocr-progress-big"><div><i id="ocrBar"></i></div><strong id="ocrPercent">0%</strong></div></div><div class="tip-stage"><small>ちょっと成分の話</small><h2 id="tipTitle">成分を確認中…</h2><p id="tipBody">読み取りながら、成分のミニ知識を表示します。</p></div><p class="ocr-wait-note">この画面のままお待ちください</p></section>`;

  S.views.ocrError=()=>`<section class="choice-screen"><span class="eyebrow">TRY AGAIN</span><h1>うまく読み取れませんでした。</h1><p>反射や小さい文字が原因かもしれません。別の方法ですぐ続けられます。</p>${btn('もう一度撮る','SEIBUN.render(\'scan\')','button primary wide')}<button class="button ghost wide" onclick="SEIBUN.render('manualInput')">文字を貼り付ける</button></section>`;
  S.views.ocrNoMatch=()=>`<section class="choice-screen"><span class="eyebrow">NEED MORE TEXT</span><h1>成分名を確認できませんでした。</h1><p>全成分欄が大きく写るように撮り直すか、テキストを貼り付けてください。</p>${btn('撮り直す','SEIBUN.render(\'scan\')','button primary wide')}<button class="button ghost wide" onclick="SEIBUN.render('manualInput')">文字を貼り付ける</button></section>`;
  S.views.manualInput=()=>`<section class="manual-screen"><span class="eyebrow">PASTE INGREDIENTS</span><h1>成分を貼り付ける。</h1><p>「水、グリセリン、ナイアシンアミド…」のように、全成分をそのまま貼り付けてOKです。</p><textarea id="manualText" rows="11" placeholder="全成分：水、グリセリン、BG、…"></textarea>${btn('この内容で見る','SEIBUN.ocr.applyManual()','button primary xl wide')}</section>`;

  S.views.productResult=()=>{const scan=S.state.lastScan;if(!scan?.found?.length)return S.views.ocrNoMatch();const p=scan.profile,r=scan.rating,recs=p?S.ingredients.recommendations(p,5):[],names=new Set(scan.found.map(x=>x.name));const present=recs.filter(x=>names.has(x.name));return `<section class="product-result"><span class="eyebrow">SCAN RESULT</span>${p&&r?`<div class="rating-card"><small>${r.provisional?'成分情報が少ないため暫定':'成分構成とのおすすめ目安'}</small>${S.stars(r.stars)}<h1>${S.starWord(r.stars)}</h1><p>${S.escape(p.code?`${p.code}｜${p.name}`:p.name)} を基準に見ています。</p></div>`:`<div class="rating-card neutral"><h1>${scan.found.length}成分を確認</h1><p>肌タイプ診断をすると、自分向けのおすすめ目安も表示できます。</p></div>`}${p?`<section class="result-mini-section"><div class="section-heading"><span>MATCH</span><h2>あなた向けに見つかった成分</h2></div>${r.relevant.length?r.relevant.map(x=>`<button class="found-benefit" onclick="SEIBUN.showIngredient('${encodeURIComponent(x.ing.name)}')"><span>✓</span><div><strong>${S.escape(x.ing.name)}</strong><small>${S.escape(x.ing.summary)}</small></div><b>›</b></button>`).join(''):'<p class="empty-copy">強く一致する成分は少なめでした。商品全体の使い心地も比較してみてください。</p>'}</section>`:''}${p&&r.cautions.length?`<section class="result-mini-section caution"><div class="section-heading"><span>CHECK</span><h2>使う前に確認したいこと</h2></div>${r.cautions.map(x=>`<div class="caution-row"><strong>${S.escape(x.ing.name)}</strong><p>${S.escape(x.text)}</p></div>`).join('')}</section>`:''}${p?`<section class="content-block"><div class="section-heading"><span>NEXT</span><h2>この肌タイプで見たい成分</h2></div>${ingredientCards(recs,p,5)}</section>`:''}<details class="ingredient-all"><summary>読み取った成分 ${scan.found.length}件</summary><div>${scan.found.map(x=>`<button onclick="SEIBUN.showIngredient('${encodeURIComponent(x.name)}')"><span>${S.escape(x.name)}</span><b>›</b></button>`).join('')}</div></details><div class="result-actions">${btn('ほかの商品も試す','SEIBUN.ocr.reset()','button primary xl wide')}${!p?`<button class="button ghost wide" onclick="SEIBUN.diagnosis.startSimple()">肌タイプをチェックする</button>`:''}</div><p class="disclaimer-mini">星は商品の安全性や効果を保証するものではなく、登録した肌傾向と確認できた成分の組み合わせによるおすすめ目安です。</p></section>`};

  S.views.ingredients=()=>{const q=S.state.dictionaryQuery||'',list=S.ingredients.search(q),show=list.slice(0,S.state.dictionaryOffset);return `<section class="dictionary-page"><div class="simple-page-head"><span class="eyebrow">DICTIONARY</span><h1>成分辞典</h1><p>気になる成分を、むずかしい言葉を減らして確認。</p></div><div class="search-box"><span>⌕</span><input value="${S.escape(q)}" placeholder="成分名・目的で検索" onkeydown="if(event.key==='Enter')SEIBUN.dictionarySearch(this.value)"><button onclick="SEIBUN.dictionarySearch(this.previousElementSibling.value)">検索</button></div><div class="dictionary-list">${show.map(x=>`<button onclick="SEIBUN.showIngredient('${encodeURIComponent(x.name)}')"><div><strong>${S.escape(x.name)}</strong><small>${S.escape(x.summary)}</small></div><b>›</b></button>`).join('')}</div>${show.length<list.length?`<button class="button ghost wide" onclick="SEIBUN.dictionaryMore()">さらに表示（残り${list.length-show.length}）</button>`:''}${!list.length?'<p class="empty-copy">該当する成分が見つかりませんでした。</p>':''}</section>`};
  S.views.ingredientDetail=()=>`<section class="plain-page">${S.ingredients.detailHtml(S.state.selectedIngredient)}</section>`;

  S.views.history=()=>{const list=S.history();return `<section class="history-page"><div class="simple-page-head"><span class="eyebrow">HISTORY</span><h1>チェック履歴</h1><p>${S.persistEnabled()?'この端末に保存中':'タブを閉じると消えます。必要なら端末保存できます。'}</p></div>${list.length?`<div class="history-list">${list.map(x=>`<article><div><small>${S.escape(x.date)}</small><strong>${S.escape(x.typeName)}</strong><p>${S.escape((x.ingredients||[]).slice(0,5).join(' / '))}</p></div>${x.stars?S.stars(x.stars):'<span>—</span>'}</article>`).join('')}</div>`:'<p class="empty-copy">まだ履歴はありません。</p>'}<details class="minimal-details settings"><summary>保存・データ設定</summary><div>${S.persistEnabled()?'<button class="button ghost wide" onclick="SEIBUN.disablePersist()">端末保存を解除</button>':'<button class="button primary wide" onclick="SEIBUN.enablePersist()">この端末に保存</button>'}<button class="text-link danger" onclick="if(confirm('保存した肌設定と履歴をすべて削除しますか？'))SEIBUN.resetAll()">すべてのデータをリセット</button></div></details></section>`};

  S.views.legal=()=>`<section class="plain-page"><article class="explain-sheet"><span class="eyebrow">NOTICE</span><h1>ご利用上の注意</h1><p>SEIBUNメガネは、化粧品選びを補助する情報サービスです。肌タイプチェックは質問への回答を整理したセルフチェックであり、医学的な診断ではありません。</p><p>成分のおすすめ目安は、成分表示から確認できた情報と登録した肌傾向を照らし合わせた参考情報です。商品の効果、安全性、アレルギーの有無を保証するものではありません。</p><p>肌トラブルが続く場合、強い痛み・腫れ等がある場合は、化粧品の使用を中止し医療機関へ相談してください。</p><p>医薬部外品の「有効成分」は、実際の商品表示で有効成分として確認できる場合に限って扱います。</p><small>更新：${APP_CONFIG.legal.updated}</small></article></section>`;

  S.afterRender=view=>{
    if(view==='scanConfirm'){const img=S.$('scanPhotoPreview');if(img&&S.state.scanFile){const url=URL.createObjectURL(S.state.scanFile);img.onload=()=>URL.revokeObjectURL(url);img.src=url}}
  };

  document.addEventListener('DOMContentLoaded',()=>{
    S.loadData();
    S.$('backBtn')?.addEventListener('click',S.back);
    document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>S.render(b.dataset.nav)));
    S.$('detailDialog')?.addEventListener('close',()=>S.ocr?.stopCamera?.());
    if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
    S.render('home',{replace:true,instant:true});
  });
})();
